services:
  vintagestory_server:
    image: ghcr.io/podiax/vintage-story-docker-server:main
    environment:
      - DATA_PATH=${DATA_PATH:-./data}
    volumes:
      - ${DATA_PATH}:/var/vintagestory/data
    ports:
      - "42420:42420"
